version: '3'
services:
    node:
        container_name: node_3
        image: "jclizano/orbis-training-docker:3.0.0"
        working_dir: /app
        ports:
            - "1045:3030"
        command: "npm start"